<a href="https://colab.research.google.com/github/krakowiakpawel9/convnet-course/blob/master/basics/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

## Skalar, Wektor, Macierz, Tensor

In [0]:
import numpy as np

### Skalar 

In [0]:
scalar = 3
print(scalar)

3


### Wektor

In [0]:
vector = np.array([2, 4, -6, 5])
print(vector)
print(type(vector))
print('Rozmiar wektora:', vector.shape)
print('Wymiar:', vector.ndim)
print('Długość:', len(vector))

[ 2  4 -6  5]
<class 'numpy.ndarray'>
Rozmiar wektora: (4,)
Wymiar: 1
Długość: 4


### Tablica ~ Macierz

In [0]:
array = np.array([[2, 6, 3],
                 [5, -3, 4]])
print(array)
print(type(array))
print('Rozmiar macierzy:', array.shape)
print('Wymiar:', array.ndim)
print('Długosc:', len(array))

[[ 2  6  3]
 [ 5 -3  4]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (2, 3)
Wymiar: 2
Długosc: 2


### Tensor 3D

In [0]:
tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [3, 7, 3]]
])

print(tensor)
print(type(tensor))
print('Rozmiar macierzy:', tensor.shape)
print('Wymiar:', tensor.ndim)
print('Długosc:', len(tensor))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (2, 2, 3)
Wymiar: 3
Długosc: 2


In [0]:
tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [3, 7, 3]],
    [[2, 3, 5],
     [7, 2, 5]]
])

print(tensor)
print(type(tensor))
print('Rozmiar macierzy:', tensor.shape)
print('Wymiar:', tensor.ndim)
print('Długosc:', len(tensor))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]

 [[2 3 5]
  [7 2 5]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (3, 2, 3)
Wymiar: 3
Długosc: 3


In [0]:
tensor = np.array([
    [[1, 2, 3, 4],
     [4, 5, 6, 4],
     [4, 2, 5, 2]],
    [[7, 8, 9, 8],
     [3, 7, 3, 9],
     [5, 2, 4, 3]],
    [[2, 3, 5, 4],
     [7, 2, 5, 1],
     [8, 2, 7, 2]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]]
])

print(tensor)
print(type(tensor))
print('Rozmiar macierzy:', tensor.shape)
print('Wymiar:', tensor.ndim)
print('Długosc:', len(tensor))

[[[1 2 3 4]
  [4 5 6 4]
  [4 2 5 2]]

 [[7 8 9 8]
  [3 7 3 9]
  [5 2 4 3]]

 [[2 3 5 4]
  [7 2 5 1]
  [8 2 7 2]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (5, 3, 4)
Wymiar: 3
Długosc: 5


In [0]:
tensor[0].shape

(3, 4)